import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(request: Request) {
  try {
    const { email, phone, name } = await request.json();

    if (!email || !phone) {
      return NextResponse.json(
        { error: "Email and Phone number are required." },
        { status: 400 }
      );
    }

    const emailHost = process.env.EMAIL_HOST || "smtp.gmail.com";
    const emailPort = parseInt(process.env.EMAIL_PORT || "465");
    const emailUser = process.env.EMAIL_USER; // Sender email username
    const emailPass = process.env.EMAIL_PASS; // Sender email app password or password
    const recipientEmail = "Qunatrixlabs@gmail.com";

    // If credentials are not configured, log details locally and return a helpful message
    if (!emailUser || !emailPass) {
      console.warn(
        "EMAIL CONFIGURATION MISSING in environment variables (EMAIL_USER / EMAIL_PASS). Lead details:",
        { name, email, phone }
      );
      return NextResponse.json({
        success: true,
        message: "Lead details logged in development console. (SMTP credentials missing for email forwarding).",
      });
    }

    // Configure SMTP transport
    const transporter = nodemailer.createTransport({
      host: emailHost,
      port: emailPort,
      secure: emailPort === 465, // true for port 465, false for other ports
      auth: {
        user: emailUser,
        pass: emailPass,
      },
    });

    const emailHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eaeaea; border-radius: 8px;">
        <h2 style="color: #4F46E5; margin-bottom: 20px;">New Qunatrix Labs Lead</h2>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #eaeaea; font-weight: bold; width: 120px;">Name:</td>
            <td style="padding: 10px 0; border-bottom: 1px solid #eaeaea;">${name || "Not provided"}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #eaeaea; font-weight: bold;">Email:</td>
            <td style="padding: 10px 0; border-bottom: 1px solid #eaeaea;"><a href="mailto:${email}">${email}</a></td>
          </tr>
          <tr>
            <td style="padding: 10px 0; border-bottom: 1px solid #eaeaea; font-weight: bold;">Phone:</td>
            <td style="padding: 10px 0; border-bottom: 1px solid #eaeaea;"><a href="tel:${phone}">${phone}</a></td>
          </tr>
        </table>
        <p style="margin-top: 30px; font-size: 11px; color: #999;">This lead notification was automatically generated by your Qunatrix Labs website.</p>
      </div>
    `;

    // Send notification email
    await transporter.sendMail({
      from: `"Qunatrix Labs Lead Capture" <${emailUser}>`,
      to: recipientEmail,
      subject: `New Lead Notification: ${name || email}`,
      text: `New Lead Details:\nName: ${name || "N/A"}\nEmail: ${email}\nPhone: ${phone}`,
      html: emailHtml,
    });

    return NextResponse.json({ success: true, message: "Email notification sent successfully." });
  } catch (error: any) {
    console.error("Email Notification Error:", error);
    return NextResponse.json(
      { error: error.message || "Internal server error." },
      { status: 500 }
    );
  }
}
